### ISSUE TITLE
INVALID

### ISSUE THREAD

**Issue by davidhedlund** [mattrude/pgpkeyserver-lite#6]
Steps to reproduce:
* Visit https://keys.gnupg.net/

or

* Visit http://keys.gnupg.net/ (not https)
* Add a valid key in the field
* Click on the Search Key button
* You will be redirected to https://keys.gnupg.net/pks/lookup?search=YOURKEY&fingerprint=on&op=index

Output:

![screenshot at 2018-06-18 17 26 13](https://user-images.githubusercontent.com/6416073/41545992-bb08838a-731c-11e8-9cac-57e212ce97b7.png)

**Comment by davidhedlund** [comment]
Once fixed I'll recommended https://keys.gnupg.net/ to [HTTP Everywhere](https://github.com/EFForg/https-everywhere/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+gnupg.net).

**Comment by vsund** [comment]
@davidhedlund I think that you came from [my keyserver](keyserver.ntzwrk.org) which lists this project in its footer. This project hasn't really to do anything with this problem (or even my keyserver ;)).
This problem is rather an infrastructural one, as keys.gnupg.net simply points to the [HKPS pool](hkps.pool.sks-keyservers.net) and servers out of this pool aren't prepared for secure requests for the domain name keys.gnupg.net (so we also can't really do anything about it).

To avoid future confusion I changed the old footer `Theme on GitHub` to `Based on Matt Rude's pgpkeyserver-lite`.

**Comment by davidhedlund** [comment]
Thanks.
